[package]
name = "forja-desktop"
version.workspace = true
edition.workspace = true
[build-dependencies]
tauri-build = { version = "2", features = [] }
[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
forja-core = { path = "../../../crates/core" }
serde_json.workspace = true
serde.workspace = true
reqwest.workspace = true
tokio.workspace = true
