import {useEffect,useState} from 'react';
import {Code2,Play,Square} from 'lucide-react';
import {api} from './api';
type Config={language:string;command:string;args:string[];available?:boolean};
export function LspControls({workspace,onError}:{workspace:string;onError:(e:unknown)=>void}){
 const [presets,setPresets]=useState<Config[]>([]),[status,setStatus]=useState<{language:string;active:boolean}[]>([]),[language,setLanguage]=useState('typescript'),[command,setCommand]=useState(''),[args,setArgs]=useState('[]'),[busy,setBusy]=useState(false);
 async function refresh(){setStatus(await api('/v1/workspaces/'+workspace+'/lsp'));}
 useEffect(()=>{let valid=true;Promise.all([api<Config[]>('/v1/lsp/presets'),api<{language:string;active:boolean}[]>('/v1/workspaces/'+workspace+'/lsp')]).then(([p,s])=>{if(!valid)return;setPresets(p);setStatus(s);const c=p.find(x=>x.language==='typescript');setCommand(c?.command??'');setArgs(JSON.stringify(c?.args??[]));}).catch(onError);return()=>{valid=false}},[workspace]);
 const active=status.find(s=>s.language===language)?.active;
 return <details className="lsp-settings"><summary><Code2 size={18}/>Inteligência de código <span>{status.filter(s=>s.active).length} servidores ativos</span></summary><p className="field-hint">Ative sugestões, tipos e diagnósticos com TypeScript Language Server ou Pyright. O programa local tem isolamento reduzido e poderá ler as dependências do projeto. F12 abre a definição dentro do workspace.</p><div className="form-grid"><label>Linguagem<select value={language} onChange={e=>{setLanguage(e.target.value);const c=presets.find(p=>p.language===e.target.value);setCommand(c?.command??'');setArgs(JSON.stringify(c?.args??[]))}}><option value="typescript">TypeScript / JavaScript</option><option value="python">Python</option></select></label><label>Executável<input value={command} onChange={e=>setCommand(e.target.value)} placeholder="C:/caminho/node.exe"/></label></div><label>Argumentos (JSON)<input value={args} onChange={e=>setArgs(e.target.value)}/></label><div className="integration-actions"><button className={active?'subtle-button':'primary-button'} disabled={busy||!command} onClick={async()=>{setBusy(true);try{if(active){await api('/v1/workspaces/'+workspace+'/lsp/'+language+'/stop','POST',{})}else{const parsed:unknown=JSON.parse(args);if(!Array.isArray(parsed)||parsed.some(a=>typeof a!=='string'))throw Error('Argumentos devem ser uma lista de textos.');await api('/v1/workspaces/'+workspace+'/lsp/start','POST',{language,command,args:parsed,confirmed:true})}await refresh()}catch(e){onError(e)}finally{setBusy(false)}}}>{active?<Square size={15}/>:<Play size={15}/>} {busy?'Aguarde…':active?'Encerrar servidor':'Autorizar e iniciar'}</button><span className={'server-state '+(active?'ready':'')}>{active?'Conectado':'Desconectado'}</span></div></details>
}
