import {useEffect,useState} from 'react';
import {Plug,Plus,RefreshCw,Shield,Unplug,Trash2,Wrench} from 'lucide-react';
import {api} from './api';
import {Modal} from './ui';

type Server={id:string;name:string;transport:'http'|'stdio';protocol_version:string;url:string;command:string;args:string[];cwd:string};
type Tool={name:string;description?:string;inputSchema:Record<string,unknown>};
type Catalog={id:string;name:string;protocol_version:string;catalog_hash:string;tools:Tool[]};
const initial={name:'',transport:'http' as 'http'|'stdio',protocol_version:'2026-07-28',url:'',command:'',args:'[]',cwd:'',token:''};
export function McpPanel({offline,onError}:{offline:boolean;onError:(e:unknown)=>void}){
 const [servers,setServers]=useState<Server[]>([]),[catalogs,setCatalogs]=useState<Catalog[]>([]),[adding,setAdding]=useState(false),[form,setForm]=useState(initial),[busy,setBusy]=useState(false);
 const [connecting,setConnecting]=useState<Server|null>(null),[removing,setRemoving]=useState<Server|null>(null),[selected,setSelected]=useState<{catalog:Catalog;tool:Tool}|null>(null),[args,setArgs]=useState('{}'),[output,setOutput]=useState('');
 async function refresh(){const [s,c]=await Promise.all([api<Server[]>('/v1/mcp/servers'),api<Catalog[]>('/v1/mcp/catalogs')]);setServers(s);setCatalogs(c);}
 useEffect(()=>{refresh().catch(onError)},[offline]);
 async function perform(action:()=>Promise<void>){setBusy(true);try{await action();await refresh()}catch(e){onError(e)}finally{setBusy(false)}}
 return <div className="integration-panel">
  <div className="integration-toolbar"><span>{servers.length} servidor{servers.length===1?'':'es'} configurado{servers.length===1?'':'s'}</span><div><button className="subtle-button" disabled={busy} onClick={()=>refresh().catch(onError)}><RefreshCw size={16}/>Atualizar</button><button className="primary-button" onClick={()=>setAdding(true)}><Plus size={17}/>Adicionar servidor</button></div></div>
  <div className="info-banner"><Shield size={20}/><div><strong>Acesso explícito, chamada por chamada</strong><p>Conectar disponibiliza o catálogo. O agente solicita aprovação para cada chamada. Servidores locais executam com isolamento reduzido; revise o programa e o diretório antes de conectar.</p></div></div>
  {offline&&<p className="cloud-notice" role="status">Modo offline ativo. Conexões MCP estão bloqueadas.</p>}
  {!servers.length&&<div className="empty-state"><Plug size={38}/><h2>Conecte suas ferramentas</h2><p>Adicione um servidor HTTP ou um programa local com transporte stdio.</p></div>}
  {servers.map(server=>{const catalog=catalogs.find(c=>c.id===server.id);return <article className="integration-card" key={server.id}>
    <header><Plug size={23}/><div><h3>{server.name}</h3><p>{server.transport==='http'?server.url:server.command} · MCP {server.protocol_version}</p></div><span className={'server-state '+(catalog?'ready':'')}>{catalog?'Conectado':'Desconectado'}</span></header>
    <div className="integration-actions">{catalog?<button className="subtle-button" disabled={busy} onClick={()=>perform(async()=>{await api('/v1/mcp/servers/'+server.id+'/disconnect','POST',{})})}><Unplug size={15}/>Desconectar</button>:<button className="subtle-button" disabled={busy||offline} onClick={()=>setConnecting(server)}><Plug size={15}/>Revisar conexão</button>}<button className="text-button" disabled={busy} onClick={()=>setRemoving(server)}><Trash2 size={14}/>Remover</button></div>
    {catalog&&<div className="mcp-tool-list">{catalog.tools.length===0?<p>Nenhuma ferramenta anunciada.</p>:catalog.tools.map(tool=><button key={tool.name} onClick={()=>{setSelected({catalog,tool});setArgs('{}');setOutput('')}}><Wrench size={16}/><span><strong>{tool.name}</strong><small>{tool.description||'Sem descrição fornecida pelo servidor.'}</small></span><span>Inspecionar</span></button>)}</div>}
  </article>})}
  {adding&&<Modal title="Adicionar servidor MCP" onClose={()=>{if(!busy)setAdding(false)}}><p className="modal-description">A configuração é local. Tokens são armazenados no cofre do sistema. Salvar não inicia o servidor.</p>
    <label>Nome<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Minhas ferramentas"/></label>
    <div className="form-grid"><label>Transporte<select value={form.transport} onChange={e=>setForm({...form,transport:e.target.value as 'http'|'stdio'})}><option value="http">HTTP</option><option value="stdio">Programa local (stdio)</option></select></label><label>Versão do protocolo<select value={form.protocol_version} onChange={e=>setForm({...form,protocol_version:e.target.value})}><option>2026-07-28</option><option>2025-11-25</option></select></label></div>
    {form.transport==='http'?<><label>Endpoint MCP<input value={form.url} onChange={e=>setForm({...form,url:e.target.value})} placeholder="https://servidor.exemplo/mcp"/></label><label>Token Bearer (opcional)<input type="password" autoComplete="off" value={form.token} onChange={e=>setForm({...form,token:e.target.value})}/></label></>:<><label>Executável<input value={form.command} onChange={e=>setForm({...form,command:e.target.value})} placeholder="C:/ferramentas/servidor.exe"/></label><label>Argumentos (lista JSON)<input value={form.args} onChange={e=>setForm({...form,args:e.target.value})} placeholder='["--stdio"]'/></label><label>Diretório de trabalho<input value={form.cwd} onChange={e=>setForm({...form,cwd:e.target.value})} placeholder="D:/meu-projeto"/></label></>}
    <footer><button className="subtle-button" disabled={busy} onClick={()=>setAdding(false)}>Cancelar</button><button className="primary-button" disabled={busy||!form.name} onClick={()=>perform(async()=>{const args=JSON.parse(form.args);if(!Array.isArray(args)||args.some(v=>typeof v!=='string'))throw Error('Os argumentos devem ser uma lista de textos.');await api('/v1/mcp/servers','POST',{...form,id:'',args});setForm(initial);setAdding(false)})}>{busy?'Salvando…':'Salvar configuração'}</button></footer>
  </Modal>}
  {connecting&&<Modal title="Revisar conexão MCP" onClose={()=>{if(!busy)setConnecting(null)}}><p className="modal-description">{connecting.transport==='stdio'?'Este programa será iniciado no computador e poderá acessar arquivos e rede com as permissões do usuário. O isolamento é reduzido.':'O FORJA enviará a identificação do cliente e consultará o catálogo deste endpoint.'}</p><pre className="review-block">{connecting.transport==='http'?connecting.url:JSON.stringify({executavel:connecting.command,argumentos:connecting.args,diretorio:connecting.cwd},null,2)}</pre><p className="field-hint">Versão {connecting.protocol_version}. Capacidades adicionais, como acesso a raízes e amostragem, não são concedidas pela conexão.</p><footer><button className="subtle-button" disabled={busy} onClick={()=>setConnecting(null)}>Cancelar</button><button className="primary-button" disabled={busy||offline} onClick={()=>perform(async()=>{await api('/v1/mcp/servers/'+connecting.id+'/connect','POST',{confirmed:true});setConnecting(null)})}>{busy?'Conectando…':'Autorizar conexão'}</button></footer></Modal>}
  {removing&&<Modal title="Remover configuração" onClose={()=>{if(!busy)setRemoving(null)}}><p className="modal-description">Remover {removing.name} desconecta o servidor e apaga seu token do cofre. O programa instalado permanece no computador.</p><footer><button className="subtle-button" disabled={busy} onClick={()=>setRemoving(null)}>Cancelar</button><button className="primary-button" disabled={busy} onClick={()=>perform(async()=>{await api('/v1/mcp/servers/'+removing.id,'DELETE');setRemoving(null)})}>Remover servidor</button></footer></Modal>}
  {selected&&<Modal title={selected.tool.name} onClose={()=>{if(!busy)setSelected(null)}}><p className="modal-description">{selected.tool.description}</p><details><summary>Schema anunciado pelo servidor</summary><pre className="review-block">{JSON.stringify(selected.tool.inputSchema,null,2)}</pre></details><label>Argumentos da chamada<textarea className="code-input" value={args} onChange={e=>setArgs(e.target.value)} spellCheck={false}/></label><p className="field-hint">Destino: {selected.catalog.name}. Autoriza somente esta chamada com os argumentos exibidos. O resultado do servidor é dado não confiável.</p><footer><button className="subtle-button" disabled={busy} onClick={()=>setSelected(null)}>Fechar</button><button className="primary-button" disabled={busy||offline} onClick={()=>perform(async()=>{setOutput('');const result=await api('/v1/mcp/servers/'+selected.catalog.id+'/call','POST',{name:selected.tool.name,arguments:JSON.parse(args),catalog_hash:selected.catalog.catalog_hash,confirmed:true});setOutput(JSON.stringify(result,null,2))})}>{busy?'Executando…':'Autorizar esta chamada'}</button></footer>{output&&<pre className="review-block" role="status">{output}</pre>}</Modal>}
 </div>
}
