import {useEffect,useRef,useState} from 'react';
import {GraduationCap,Plus,Check,RefreshCw} from 'lucide-react';
import {api} from './api';import {Modal} from './ui';import type {Workspace} from './types';
import {SkillResources,type SkillEntry as Skill} from './SkillPicker';
const example='---\nname: revisar-codigo\ndescription: Revisar alterações e registrar evidências de testes.\n---\nLeia o diff do projeto. Identifique problemas concretos e indique arquivos e linhas.\n';
export function SkillsPanel({workspace,onError}:{workspace:Workspace|null;onError:(e:unknown)=>void}){
 const [skills,setSkills]=useState<Skill[]>([]),[create,setCreate]=useState(false),[content,setContent]=useState(example),[busy,setBusy]=useState(false),[validation,setValidation]=useState('');
 const pending=useRef(0),[loading,setLoading]=useState(false);
 async function refresh(){if(!workspace)return;const current=++pending.current;setLoading(true);try{const rows=await api<Skill[]>('/v1/workspaces/'+workspace.id+'/skills');if(current===pending.current)setSkills(rows)}finally{if(current===pending.current)setLoading(false)}}
 useEffect(()=>{setSkills([]);refresh().catch(onError);return()=>{pending.current++}},[workspace?.id]);
 if(!workspace)return <div className="empty-state"><GraduationCap size={36}/><h2>Abra um projeto</h2><p>Crie e inspecione skills armazenadas no workspace.</p></div>;
 return <><div className="integration-toolbar"><span>Skills de {workspace.name}</span><div><button className="subtle-button" disabled={loading||busy} onClick={()=>refresh().catch(onError)}><RefreshCw size={16}/>Atualizar catálogo</button><button className="primary-button" onClick={()=>{setCreate(true);setValidation('')}}><Plus size={16}/>Criar skill</button></div></div><p className="field-hint">Os arquivos são descobertos em skills e .forja/skills. O agente recebe primeiro os nomes e descrições. Instruções e referências são carregadas quando necessárias, com origem e hash registrados. Skills não concedem permissões de execução.</p>{skills.map(s=><details className="skill-card" key={workspace.id+s.path+(s.hash??s.error)}><summary><GraduationCap size={21}/><div><strong>{s.name||'Skill sem nome'}</strong><p>{s.description}</p></div><span>{s.valid?'Formato válido':'Revisar formato'}</span></summary><small>{s.path}</small>{s.error&&<p role="alert" className="backup-error">{s.error}</p>}{s.hash&&<small>SHA-256: {s.hash}</small>}{s.content&&<pre>{s.content}</pre>}{s.valid&&<SkillResources workspace={workspace.id} skill={s}/>}</details>)}{!loading&&!skills.length&&<div className="empty-state"><GraduationCap size={36}/><h2>Sua biblioteca começa aqui</h2><p>Crie uma skill com orientações úteis para este projeto.</p></div>}
 {create&&<Modal title="Criar skill" onClose={()=>{if(!busy)setCreate(false)}}><p className="modal-description">O nome define a pasta skills/nome/SKILL.md. O arquivo existente nunca será sobrescrito.</p><label>Conteúdo de SKILL.md<textarea className="code-input skill-input" value={content} onChange={e=>{setContent(e.target.value);setValidation('')}} spellCheck={false}/></label>{validation&&<p className="probe-result" role="status"><Check size={15}/> {validation}</p>}<footer><button className="subtle-button" disabled={busy} onClick={async()=>{try{const v=await api('/v1/skills/validate','POST',{content});setValidation('Formato válido: '+v.name)}catch(e){onError(e)}}}>Validar formato</button><button className="primary-button" disabled={busy} onClick={async()=>{setBusy(true);try{await api('/v1/workspaces/'+workspace.id+'/skills','POST',{content});await refresh();setCreate(false);setContent(example)}catch(e){onError(e)}finally{setBusy(false)}}}>{busy?'Salvando…':'Salvar no projeto'}</button></footer></Modal>}
 </>
}
